[versions]

[libraries]
annotations = "org.jetbrains:annotations:26.0.2-1"
paper = "io.papermc.paper:paper-api:1.20.6-R0.1-SNAPSHOT"
nexo = "com.nexomc:nexo:1.17.0"
oraxen = "io.th0rgal:oraxen:1.205.0"
itemsadder = "dev.lone:api-itemsadder:4.0.10"

junit-bom = "org.junit:junit-bom:6.0.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-platform = { module = "org.junit.platform:junit-platform-launcher" }

[bundles]
junit = ["junit-jupiter", "junit-platform"]

[plugins]
publisher = "com.vanniktech.maven.publish:0.36.0"
